name: build

on:
  push:
    branches: [ci]
  pull_request:
    branches: [ci]

jobs:
  build:
    name: Build and Test Rust Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable  # Ensures stable Rust version

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Build project
        run: cargo build --release

      - name: Run tests
        run: cargo test --release
